# Bert embeddings test

In [6]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer("dangvantuan/sentence-camembert-base")

sentences = ["Un avion est en train de décoller.",
          "Un homme joue d'une grande flûte.",
          "Un homme étale du fromage râpé sur une pizza.",
          "Une personne jette un chat au plafond.",
          "Une personne est en train de plier un morceau de papier.",
          ]

embeddings = model.encode(sentences)
embeddings[0]

array([-7.64306933e-02,  1.32608980e-01,  3.91310900e-02,  1.45144640e-02,
        6.81611449e-02,  6.43291324e-02, -1.54538468e-01, -2.95928353e-03,
        9.13087279e-02,  9.12379753e-03,  9.03712511e-02, -3.38764442e-03,
       -9.02096033e-02, -1.21561266e-01,  6.59199432e-02, -1.93026625e-02,
        1.18438147e-01,  8.82427394e-02, -1.87649280e-01,  1.15828797e-01,
        8.50065947e-02,  4.02593538e-02, -1.83811426e-01, -9.49616432e-02,
        6.39294535e-02, -1.13634132e-01,  4.83636782e-02, -7.36181512e-02,
        4.09527048e-02,  4.30823974e-02, -1.41970366e-01, -1.77941248e-01,
        1.05397619e-01, -8.70714150e-03, -1.06472507e-01,  2.03699972e-02,
        9.32977349e-02, -4.58931625e-02,  7.94660859e-03,  1.05612203e-01,
       -2.82531437e-02, -1.35584086e-01, -5.72142825e-02, -4.37538326e-03,
       -8.91788453e-02,  1.64472014e-01,  2.20994666e-01,  2.67969677e-03,
       -2.67329905e-02, -1.12966634e-01, -4.56892252e-02,  6.19257167e-02,
       -7.23673776e-02,  

# Create Dataset with embeddings

In [45]:
from ml_logic.data_mysql import db_to_dataframe
from datetime import datetime
news_df = db_to_dataframe(nb_rows=1000)
news_df.head(10)

DataFrame retrieve from MySQL
     news_id  category_id                                              title  \
0     168739            8  Vosges. La « Boucherie des 3 vallées » à Anoul...   
1     168740            8  Éducation. Plusieurs lycées des Vosges visés p...   
2     168741            8  Vosges. Gérardmer : quatre bonnes raisons de s...   
3     168742            8  Vosges. Menace attentat : “On a cru à un exerc...   
4     168743            8  Vosges. Plus aucun train ne circule entre Épin...   
..       ...          ...                                                ...   
995   168498            8  Première prise de parole après son élection, D...   
996   168499            8  Présidentielle : Le Général Doumbouya félicite...   
997   168500            8  Le président de l’Assemblée nationale félicite...   
998   168501            8  Le président élu, Bassirou Diomaye Faye va s’a...   
999   168502            8  Habib Diallo : « Le début de saison a été comp...   

         

news_id  category_id                                              title  \
0   168739            8  Vosges. La « Boucherie des 3 vallées » à Anoul...   
1   168740            8  Éducation. Plusieurs lycées des Vosges visés p...   
2   168741            8  Vosges. Gérardmer : quatre bonnes raisons de s...   
3   168742            8  Vosges. Menace attentat : “On a cru à un exerc...   
4   168743            8  Vosges. Plus aucun train ne circule entre Épin...   
5   168744            8  Photos. Remiremont : au moins six voitures inc...   
6   168745            8  Vosges. Un ouvrier tombe d’un toit haut de 5 m...   
7   168746            8  Biopic #15 : Ibn Khaldoun, père fondateur des ...   
8   168747            8  «Laayoune au Maroc» : Le ministre espagnol de ...   
9   168748            8  Affaire «Escobar du Sahara» : Les accusations ...   

                                         description  \
0  La boucherie a ouvert à la mi-janvier dans un ...   
1  Depuis ce lundi matin, différents lycées des V...   
2  Samedi, dimanche et lundi : durant tout le wee...   
3  Des élèves de cinq lycées des Vosges ont été é...   
4  Depuis ce samedi 23 mars, plus aucun train ne ...   
5  C'est le choc à Remiremont. Jamais la ville n'...   
6  Un ouvrier est décédé ce lundi matin à Senaide...   
7  Ibn Khaldoun consacra sa vie à parcourir les p...   
8  La publication au Bulletin officiel de l’Espag...   
9  A l’issue de la procédure d’instruction visant...   

                                                link image  \
0  https://www.vosgesmatin.fr/economie/2024/03/26...         
1  https://www.vosgesmatin.fr/education/2024/03/2...         
2  https://www.vosgesmatin.fr/culture-loisirs/202...         
3  https://www.vosgesmatin.fr/education/2024/03/2...         
4  https://www.vosgesmatin.fr/economie/2024/03/25...         
5  https://www.vosgesmatin.fr/faits-divers-justic...         
6  https://www.vosgesmatin.fr/faits-divers-justic...         
7  https://www.yabiladi.com/articles/details/7853...         
8  https://www.yabiladi.com/articles/details/1480...         
9  https://www.yabiladi.com/articles/details/1480...         

           added_date                            source sub_cat  \
0 2024-03-26 09:00:00  Vosges Matin : toute l'actualité  presse   
1 2024-03-26 09:00:00  Vosges Matin : toute l'actualité  presse   
2 2024-03-26 09:00:00  Vosges Matin : toute l'actualité  presse   
3 2024-03-26 09:00:00  Vosges Matin : toute l'actualité  presse   
4 2024-03-26 09:00:00  Vosges Matin : toute l'actualité  presse   
5 2024-03-26 09:00:00  Vosges Matin : toute l'actualité  presse   
6 2024-03-26 09:00:00  Vosges Matin : toute l'actualité  presse   
7 2024-03-26 09:00:00                          Yabiladi           
8 2024-03-26 09:00:00                          Yabiladi           
9 2024-03-26 09:00:00                          Yabiladi           

                                           embedding  
0  [0.0, 1.4773215055465698, -3.6893488147419103e...  
1  [3.6893488147419103e+19, 1.3820072412490845, -...  
2  [1.0842021724855044e-19, 1.5502405166625977, -...  
3  [-0.0, -1.0121217966079712, 1.0842021724855044...  
4  [-0.0, -1.1510285139083862, -0.0, -1.511612296...  
5  [2.0, 1.2325842380523682, -2.0, -1.50130379199...  
6  [-2.0, 1.313790202140808, -0.0, -1.30133414268...  
7  [2.0, 0.9875894784927368, -0.0, 1.381697535514...  
8  [-0.0, 1.3951424360275269, -2.0, -1.4406043291...  
9  [-0.0, 1.3409841060638428, -2.0, -1.3526464700...

In [48]:
len(news_df.iloc[999]['embedding'])

1536

In [49]:
import pandas as pd

title_and_description = news_df.head(10).apply(lambda row: row['title'] + ' ' + row['description'], axis=1)
news_embedded = model.encode(title_and_description)
news_df['embedding'] = pd.Series(news_embedded.tolist())

In [52]:
news_df

news_id  category_id                                              title  \
0     168739            8  Vosges. La « Boucherie des 3 vallées » à Anoul...   
1     168740            8  Éducation. Plusieurs lycées des Vosges visés p...   
2     168741            8  Vosges. Gérardmer : quatre bonnes raisons de s...   
3     168742            8  Vosges. Menace attentat : “On a cru à un exerc...   
4     168743            8  Vosges. Plus aucun train ne circule entre Épin...   
..       ...          ...                                                ...   
995   168498            8  Première prise de parole après son élection, D...   
996   168499            8  Présidentielle : Le Général Doumbouya félicite...   
997   168500            8  Le président de l’Assemblée nationale félicite...   
998   168501            8  Le président élu, Bassirou Diomaye Faye va s’a...   
999   168502            8  Habib Diallo : « Le début de saison a été comp...   

                                           description  \
0    La boucherie a ouvert à la mi-janvier dans un ...   
1    Depuis ce lundi matin, différents lycées des V...   
2    Samedi, dimanche et lundi : durant tout le wee...   
3    Des élèves de cinq lycées des Vosges ont été é...   
4    Depuis ce samedi 23 mars, plus aucun train ne ...   
..                                                 ...   
995  Bassirou Diomaye Faye, président de la républi...   
996  Le Général Doumbouya félicite le président Bas...   
997  Le président de l&#8217;Assemblée nationale a ...   
998  Vingt-quatre heures après le scrutin de l’élec...   
999  L’attaquant sénégalais faisait face à la press...   

                                                  link image  \
0    https://www.vosgesmatin.fr/economie/2024/03/26...         
1    https://www.vosgesmatin.fr/education/2024/03/2...         
2    https://www.vosgesmatin.fr/culture-loisirs/202...         
3    https://www.vosgesmatin.fr/education/2024/03/2...         
4    https://www.vosgesmatin.fr/economie/2024/03/25...         
..                                                 ...   ...   
995  https://senegal7.com/premiere-prise-de-parole-...         
996  https://senegal7.com/presidentielle-le-general...         
997  https://senegal7.com/le-president-de-lassemble...         
998  https://senegal7.com/le-president-elu-bassirou...         
999  https://senegal7.com/habib-diallo-le-debut-de-...         

             added_date                            source sub_cat  \
0   2024-03-26 09:00:00  Vosges Matin : toute l'actualité  presse   
1   2024-03-26 09:00:00  Vosges Matin : toute l'actualité  presse   
2   2024-03-26 09:00:00  Vosges Matin : toute l'actualité  presse   
3   2024-03-26 09:00:00  Vosges Matin : toute l'actualité  presse   
4   2024-03-26 09:00:00  Vosges Matin : toute l'actualité  presse   
..                  ...                               ...     ...   
995 2024-03-26 09:00:00                         Sénégal 7           
996 2024-03-26 09:00:00                         Sénégal 7           
997 2024-03-26 09:00:00                         Sénégal 7           
998 2024-03-26 09:00:00                         Sénégal 7           
999 2024-03-26 09:00:00                         Sénégal 7           

                                             embedding  
0    [0.11366075277328491, -0.002501565730199218, -...  
1    [0.06600364297628403, -0.02370978519320488, 0....  
2    [0.17524053156375885, -0.06171458587050438, -0...  
3    [-0.008570116013288498, -0.19270958006381989, ...  
4    [-0.018878571689128876, -0.13661235570907593, ...  
..                                                 ...  
995                                                NaN  
996                                                NaN  
997                                                NaN  
998                                                NaN  
999                                                NaN  

[1000 rows x 10 columns]

# Compute similarity

In [29]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

def compute_cosine_similarity(first_embedding, second_embedding):
    dot_product = np.dot(first_embedding, second_embedding)

    norm_first_emb = np.linalg.norm(first_embedding)
    norm_second_emb = np.linalg.norm(second_embedding)

    cosine_sim = dot_product / (norm_first_emb * norm_second_emb)
    return cosine_sim

def compute_jaccard_similarity(first_embedding, second_embedding):
    intersection = np.logical_and(first_embedding, second_embedding).sum()
    union = np.logical_or(first_embedding, second_embedding).sum()
    jac_sim = intersection / union if union != 0 else 0
    return jac_sim

def compute_euclidean_distance(first_embedding, second_embedding):
    return np.linalg.norm(first_embedding - second_embedding)

def compute_manhattan_distance(first_embedding, second_embedding):
    return np.sum(np.abs(first_embedding - second_embedding))

In [30]:
from ml_logic.data_mysql import get_last_news_liked

last_liked = get_last_news_liked(3, list(np.arange(1,14))).apply(lambda row: row['title'] + ' ' + row['description'], axis=1)
last_liked_emb = model.encode(last_liked)
last_liked_emb

------------LAST NEWS LIKED BY {user_id} retrieve -------------
   news_id  category_id                             title  \
0   128635            8  «Bright Future», Adrianne Lenker   

                                         description  \
0  Le sixième album de la leader de l’excellent o...   

                                                link image  \
0  https://www.ledevoir.com/culture/musique/80951...         

           added_date     source sub_cat  \
0 2024-03-22 09:00:00  Le Devoir           

                                           embedding  
0  b'\x00\x00\x00\x80\xfdU\xa0?\x00\x00\x00\xa0/$...  
-------------------------


array([[ 3.19060087e-02, -5.30105978e-02, -2.11570561e-02,
         3.75965908e-02, -9.50383954e-03, -3.67844440e-02,
        -2.49839071e-02,  5.18798828e-02,  5.07627912e-02,
         2.32291427e-02,  4.39069942e-02, -8.44730414e-04,
         3.88790481e-02, -8.11342150e-02,  1.12596318e-01,
         2.52063889e-02,  1.86064422e-01,  8.33525434e-02,
         1.12538459e-03, -6.61955448e-03, -3.14263850e-02,
         4.19800356e-02,  1.70646280e-01,  1.66230500e-02,
         1.44113198e-01,  1.28139714e-02, -2.79631764e-02,
        -1.77447591e-02,  3.41867916e-02,  4.41122465e-02,
        -1.25863090e-01,  6.62880763e-02, -8.07949305e-02,
         1.51572078e-02,  3.31838476e-03, -5.51747978e-02,
        -1.52919263e-01, -6.17998205e-02, -4.29132283e-02,
         1.68083534e-01,  3.60095724e-02,  1.14567252e-02,
        -6.41864985e-02,  4.69524972e-02,  9.92619200e-04,
         1.43052235e-01,  8.48456919e-02,  2.25429218e-02,
        -5.50515242e-02, -9.09741595e-03,  9.55893099e-0

In [43]:
def get_top_similar_news(news_embedded, news_df, num_recommendations, method='cosine'):
    # Map method to associated function
    similarity_functions = {
        'cosine': compute_cosine_similarity,
        'euclidean': compute_euclidean_distance,
        'manhattan': compute_manhattan_distance,
        'jaccard': compute_jaccard_similarity
    }
    if method not in similarity_functions:
        raise ValueError("Invalid method. Valid options are 'cosine', 'euclidean', 'manhattan', and 'jaccard'.")

    # Compute the similaritues
    similarity_function = similarity_functions[method]
    similarities = []
    for idx, row in news_df.iterrows():
        print(len(row['embedding']))
        similarity = similarity_function(news_embedded, row['embedding'])
        similarities.append((idx, similarity))

    # Retrieve the best news
    if method in ['cosine', 'jaccard']:
        sorted_similarities = sorted(similarities, key=lambda x: x[1], reverse=True)
    else:
        sorted_similarities = sorted(similarities, key=lambda x: x[1])

    top_similar_news_indices = [idx for idx, _ in sorted_similarities[:num_recommendations]]
    top_similar_news = news_df.loc[top_similar_news_indices]

    return top_similar_news

In [44]:
get_top_similar_news(last_liked_emb, news_df, 10, method='cosine')

1536


ValueError: shapes (1,768) and (1536,) not aligned: 768 (dim 1) != 1536 (dim 0)

# Editing DB to add embeddings

In [4]:
import sqlalchemy
from ml_logic.data_mysql import getconn

In [50]:
news_df = db_to_dataframe()

title_and_description = news_df.apply(lambda row: row['title'] + ' ' + row['description'], axis=1)
news_embedded = model.encode(title_and_description)
news_df['embedding'] = pd.Series(news_embedded.tolist())
news_df

DataFrame retrieve from MySQL


news_id  category_id  \
0             1            1   
1             2            1   
2             3            1   
3             4            1   
4             5            1   
...         ...          ...   
127711   129609           12   
127712   129610           12   
127713   129611           12   
127714   129612            6   
127715   129613            6   

                                                    title  \
0                        Analyse d’un roman (68e épisode)   
1       Un remake annoncé pour ce film culte des année...   
2       Equilibrium : pourquoi ça aurait dû être un gr...   
3       Furiosa : George Miller explique pourquoi il a...   
4       Ce vidéoprojecteur 4K LG profite d'une remise ...   
...                                                   ...   
127711  "La princesse va bien, à présent" : Albert II ...   
127712  "J'aurai du mal à en parler au passé" : Stépha...   
127713  L'ancien ministre Frédéric Mitterrand est mort...   
127714  IA : Microsoft déploie les grands moyens pour ...   
127715  Thales Belfast, cette usine qui produit des mi...   

                                              description  \
0       Dans ce nouvel épisode de la série « L’Alchimi...   
1       Les producteurs du Discours d'un roi ont annon...   
2       Film de science-fiction sorti au cinéma en 200...   
3       Le réalisateur George Miller est revenu sur la...   
4       Reconnu comme l'un des meilleurs modèles à ult...   
...                                                   ...   
127711  Le prince Albert II de Monaco s'est confié sur...   
127712  Stéphane Bern a appris en direct la mort de Fr...   
127713  Jeudi 21 mars 2024, Frédéric Mitterrand est dé...   
127714  Sous la houlette de Satya Nadella, le géant in...   
127715  REPORTAGE - L’usine nord-irlandaise de Thales ...   

                                                     link  \
0       https://www.aproposdecriture.com/analyse-dun-r...   
1       https://www.ecranlarge.com/films/news/1505931-...   
2       https://www.ecranlarge.com/films/news/1505944-...   
3       https://www.ecranlarge.com/films/news/1505918-...   
4       https://www.ecranlarge.com/high-tech/news/1505...   
...                                                   ...   
127711  https://www.femmeactuelle.fr/actu/news-actu/la...   
127712  https://www.femmeactuelle.fr/actu/news-actu/j-...   
127713  https://www.femmeactuelle.fr/actu/news-actu/l-...   
127714  https://www.challenges.fr/entreprise/ia-plus-p...   
127715  https://www.challenges.fr/entreprise/defense/g...   

                                                    image          added_date  \
0                                                         2024-03-21 09:00:00   
1                                                         2024-03-21 09:00:00   
2                                                         2024-03-21 09:00:00   
3                                                         2024-03-21 09:00:00   
4                                                         2024-03-21 09:00:00   
...                                                   ...                 ...   
127711  https://fac.img.pmdstatic.net/fit/~1~voi~2023~... 2024-03-22 09:00:00   
127712  https://fac.img.pmdstatic.net/fit/~1~fac~2024~... 2024-03-22 09:00:00   
127713  https://fac.img.pmdstatic.net/fit/~1~fac~2021~... 2024-03-22 09:00:00   
127714                                                    2024-03-22 09:00:00   
127715                                                    2024-03-22 09:00:00   

                     source      sub_cat  \
0       À propos d'écriture  litterature   
1               Écran large       cinema   
2               Écran large       cinema   
3               Écran large       cinema   
4               Écran large       cinema   
...                     ...          ...   
127711       Femme actuelle     feminine   
127712       Femme actuelle     feminine   
127713       Femme actuelle     feminine   
127714     

In [53]:
from ml_logic.data_mysql import getconn

pool = sqlalchemy.create_engine(
        "mysql+pymysql://",
        creator=getconn,
    )
conn = pool.connect()

query = sqlalchemy.text("""
    ALTER TABLE news_dataset
    ADD COLUMN embedding BLOB
""")
conn.execute(query)

In [58]:
pool = sqlalchemy.create_engine(
        "mysql+pymysql://",
        creator=getconn,
    )
conn = pool.connect()

for idx, row in news_df.iterrows():
    params={'embedding': np.array(row['embedding']).tobytes(),
        'news_id': row['news_id']}

    query = sqlalchemy.text("""
        UPDATE news_dataset
        SET embedding = :embedding
        WHERE news_id = :news_id
    """)

    conn.execute(query, parameters=params)

conn.commit()
print("Embeddings added to the database.")

Embeddings added to the database.


# Compute the mean embeddings

In [47]:
def compute_embedding_mean(embeddings):
    if embeddings.empty:
        raise ValueError("The embeddings passed are empty")
    embeddings_array = np.array(embeddings.tolist())
    mean_embedding = np.mean(embeddings_array, axis=0)
    return mean_embedding

# Lecture des embeddings

In [59]:
embeddings_df = db_to_dataframe(10)

decoded_embeddings = []
for idx, row in embeddings_df.iterrows():
    embedding_bytes = row['embedding']
    embedding_array = np.frombuffer(embedding_bytes, dtype=np.float32)
    decoded_embeddings.append(embedding_array)

decoded_embeddings

DataFrame retrieve from MySQL


[array([ 3.6893488e+19, -1.1054986e+00,  1.0842022e-19, ...,
        -1.3972992e+00,  2.0000000e+00,  1.1855617e+00], dtype=float32),
 array([-1.0842022e-19, -1.1735511e+00, -2.0000000e+00, ...,
        -1.3615949e+00, -2.0000000e+00,  1.4499897e+00], dtype=float32),
 array([ 1.0842022e-19, -1.1130826e+00,  3.6893488e+19, ...,
         1.3966033e+00, -0.0000000e+00,  1.3920240e+00], dtype=float32),
 array([-3.6893488e+19,  1.5122596e+00, -0.0000000e+00, ...,
         1.1705309e+00, -3.6893488e+19,  1.2049527e+00], dtype=float32),
 array([-3.6893488e+19,  1.5196768e+00,  1.0842022e-19, ...,
        -8.5178334e-01, -3.6893488e+19,  1.3439808e+00], dtype=float32),
 array([-2.        , -0.812992  , -0.        , ...,  0.96295124,
         2.        , -1.2015364 ], dtype=float32),
 array([-1.0842022e-19, -1.2842952e+00,  2.0000000e+00, ...,
         1.0631794e+00, -3.6893488e+19,  1.5069513e+00], dtype=float32),
 array([-0.       , -1.275765 , -0.       , ...,  0.9794823, -0.       ,
       

['the-mdr-project:europe-west1:mdr-project']: An error occurred while performing refresh. Scheduling another refresh attempt immediately
Traceback (most recent call last):
  File "/Users/mathieuna/.pyenv/versions/3.10.6/envs/the_mdr_project/lib/python3.10/site-packages/google/cloud/sql/connector/instance.py", line 312, in _refresh_task
    refresh_data = await refresh_task
  File "/Users/mathieuna/.pyenv/versions/3.10.6/envs/the_mdr_project/lib/python3.10/site-packages/google/cloud/sql/connector/instance.py", line 260, in _perform_refresh
    ephemeral_cert, expiration = await ephemeral_task
  File "/Users/mathieuna/.pyenv/versions/3.10.6/envs/the_mdr_project/lib/python3.10/site-packages/google/cloud/sql/connector/client.py", line 193, in _get_ephemeral
    resp = await self._client.post(
  File "/Users/mathieuna/.pyenv/versions/3.10.6/envs/the_mdr_project/lib/python3.10/site-packages/aiohttp/client.py", line 605, in _request
    await resp.start(conn)
  File "/Users/mathieuna/.pyenv/v

# Adding embedding where it is missing

In [2]:
from ml_logic.data_mysql import db_to_dataframe, getconn
from datetime import datetime
import sqlalchemy
import pandas as pd

pool = sqlalchemy.create_engine(
        "mysql+pymysql://",
        creator=getconn,
    )
conn = pool.connect()

query = """
        SELECT *
        FROM news_dataset
        WHERE embedding IS NULL
        """

result = pd.read_sql_query(query, conn)

In [3]:
result.head(5)

news_id  category_id                                              title  \
0   168764            1  Mission Impossible 2 : Tom Cruise a terrifié l...   
1   168765            1  Pirates des Caraïbes 6 arrive, c'est officiel ...   
2   168766            1  Le miracle de La Zone d'intérêt : après les Os...   
3   168767            1  Alien Romulus : la bande-annonce fait un clin ...   
4   168768            1  Bad Boys 4 : une bande-annonce en cavale pour ...   

                                         description  \
0  Tom Cruise a terrifié son réalisateur John Woo...   
1  C'est officiel, Pirates des Caraïbes 6 va tout...   
2  Après avoir été récompensé à Cannes et aux Osc...   
3  La première bande-annonce d'Alien : Romulus co...   
4  Will Smith et Martin Lawrence sont traqués dan...   

                                                link image  \
0  https://www.ecranlarge.com/films/news/1506599-...         
1  https://www.ecranlarge.com/films/news/1506590-...         
2  https://www.ecranlarge.com/films/dossier/15065...         
3  https://www.ecranlarge.com/films/news/1506570-...         
4  https://www.ecranlarge.com/films/news/1506575-...         

           added_date       source sub_cat embedding  
0 2024-03-27 09:00:00  Écran large  cinema      None  
1 2024-03-27 09:00:00  Écran large  cinema      None  
2 2024-03-27 09:00:00  Écran large  cinema      None  
3 2024-03-27 09:00:00  Écran large  cinema      None  
4 2024-03-27 09:00:00  Écran large  cinema      None

In [6]:
len(result.iloc[0]['embedding'])

768

In [4]:
title_and_description = result.apply(lambda row: row['title'] + ' ' + row['description'], axis=1)
news_embedded = model.encode(title_and_description)
result['embedding'] = pd.Series(news_embedded.tolist())
result

news_id  category_id  \
0       168764            1   
1       168765            1   
2       168766            1   
3       168767            1   
4       168768            1   
...        ...          ...   
12119   180883           12   
12120   180884           12   
12121   180885           12   
12122   180886           12   
12123   180887           12   

                                                   title  \
0      Mission Impossible 2 : Tom Cruise a terrifié l...   
1      Pirates des Caraïbes 6 arrive, c'est officiel ...   
2      Le miracle de La Zone d'intérêt : après les Os...   
3      Alien Romulus : la bande-annonce fait un clin ...   
4      Bad Boys 4 : une bande-annonce en cavale pour ...   
...                                                  ...   
12119  Santé cérébrale : ce type de produit augmenter...   
12120  Horoscope du mercredi 27 mars 2024 par Isabell...   
12121  "Toutes ces filles lui tournaient autour" : Do...   
12122  EXCLU - “C’est quelqu’un de très doux” : les c...   
12123  Kate Middleton : après l’annonce du cancer de ...   

                                             description  \
0      Tom Cruise a terrifié son réalisateur John Woo...   
1      C'est officiel, Pirates des Caraïbes 6 va tout...   
2      Après avoir été récompensé à Cannes et aux Osc...   
3      La première bande-annonce d'Alien : Romulus co...   
4      Will Smith et Martin Lawrence sont traqués dan...   
...                                                  ...   
12119  Des chercheurs américains estiment que l'expos...   
12120  Grande joie ou petits tracas, à quoi ressemble...   
12121  Dominique Tapie a confié dans une vidéo de la ...   
12122  Véronika Loubry a accordé une longue interview...   
12123  Le roi Charles III a décidé de prendre la paro...   

                                                    link  \
0      https://www.ecranlarge.com/films/news/1506599-...   
1      https://www.ecranlarge.com/films/news/1506590-...   
2      https://www.ecranlarge.com/films/dossier/15065...   
3      https://www.ecranlarge.com/films/news/1506570-...   
4      https://www.ecranlarge.com/films/news/1506575-...   
...                                                  ...   
12119  https://www.femmeactuelle.fr/sante/news-sante/...   
12120  https://www.femmeactuelle.fr/horoscope2/vos-pr...   
12121  https://www.femmeactuelle.fr/actu/news-actu/to...   
12122  https://www.femmeactuelle.fr/actu/news-actu/ex...   
12123  https://www.femmeactuelle.fr/actu/news-actu/ka...   

                                                   image          added_date  \
0                                                        2024-03-27 09:00:00   
1                                                        2024-03-27 09:00:00   
2                                                        2024-03-27 09:00:00   
3                                                        2024-03-27 09:00:00   
4                                                        2024-03-27 09:00:00   
...                                                  ...                 ...   
12119  https://fac.img.pmdstatic.net/fit/~1~fac~2024~... 2024-03-27 09:00:00   
12120  https://fac.img.pmdstatic.net/fit/~1~fac~2023~... 2024-03-27 09:00:00   
12121  https://fac.img.pmdstatic.net/fit/~1~fac~2023~... 2024-03-27 09:00:00   
12122  https://fac.img.pmdstatic.net/fit/~1~fac~2024~... 2024-03-27 09:00:00   
12123  https://fac.img.pmdstatic.net/fit/~1~fac~2024~... 2024-03-27 09:00:00   

               source   sub_cat  \
0         Écran large    cinema   
1         Écran large    cinema   
2         Écran large    cinema   
3         Écran large    cinema   
4         Écran large    cinema   
...               ...       ...   
12119  Femme actuelle  feminine   
12120  Femme actuelle  feminine   
12121  Femme actuelle  feminine   
12122  Femme actuelle  feminine   
12123  Femme actuelle  feminine   

                                               embedding  
0      [-0.05701412633061409, 

In [5]:
import numpy as np

pool = sqlalchemy.create_engine(
        "mysql+pymysql://",
        creator=getconn,
    )
conn = pool.connect()

for idx, row in result.iterrows():
    params={'embedding': np.array(row['embedding']).tobytes(),
        'news_id': row['news_id']}

    query = sqlalchemy.text("""
        UPDATE news_dataset
        SET embedding = :embedding
        WHERE news_id = :news_id
    """)

    conn.execute(query, parameters=params)

conn.commit()
print("Embeddings added to the database.")

Embeddings added to the database.


In [ ]:
from ml_logic.data_mysql import db_to_dataframe, getconn
from datetime import datetime
import sqlalchemy
import pandas as pd

pool = sqlalchemy.create_engine(
        "mysql+pymysql://",
        creator=getconn,
    )
conn = pool.connect()

query = """
        SELECT *
        FROM news_dataset
        WHERE news_id > 168759
        """

result = pd.read_sql_query(query, conn)

['the-mdr-project:europe-west1:mdr-project']: An error occurred while performing refresh. Scheduling another refresh attempt immediately
Traceback (most recent call last):
  File "/Users/mathieuna/.pyenv/versions/3.10.6/envs/the_mdr_project/lib/python3.10/site-packages/aiohttp/connector.py", line 1173, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/Users/mathieuna/.pyenv/versions/3.10.6/envs/the_mdr_project/lib/python3.10/site-packages/aiohttp/connector.py", line 884, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/Users/mathieuna/.pyenv/versions/3.10.6/envs/the_mdr_project/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/Users/mathieuna/.pyenv/versions/3.10.6/lib/python3.10/asyncio/base_events.py", line 860, in getaddrinfo
    return await self.run_in_executor(
  File "/Users/mathieuna/.pyenv/versions/3.10.6/lib/python3.10/

In [9]:
result

news_id  category_id                                              title  \
0   168760           12  Patrick Sébastien : cette photo de l’animateur...   
1   168761           12  Ce changement à l’aéroport qui devrait vous fa...   
2   168762           12  Ingrid Chauvin : son tendre hommage à sa fille...   
3   168763           12  “Un jour, il m'a jetée dans l'escalier” : le t...   

                                         description  \
0  Le 24 mars 2024, une photo de Patrick Sébastie...   
1  Le 19 mars 2024, à l'aéroport de Roissy, l'int...   
2  Le 25 mars 2024 marque le dixième anniversaire...   
3  Lundi 25 mars 2024, dans l'émission Ça commenc...   

                                                link  \
0  https://www.femmeactuelle.fr/actu/news-actu/pa...   
1  https://www.femmeactuelle.fr/actu/news-actu/ce...   
2  https://www.femmeactuelle.fr/actu/news-actu/in...   
3  https://www.femmeactuelle.fr/actu/news-actu/un...   

                                               image          added_date  \
0  https://fac.img.pmdstatic.net/fit/~1~fac~2024~... 2024-03-26 09:00:00   
1  https://fac.img.pmdstatic.net/fit/~1~fac~2024~... 2024-03-26 09:00:00   
2  https://fac.img.pmdstatic.net/fit/~1~fac~2021~... 2024-03-26 09:00:00   
3  https://fac.img.pmdstatic.net/fit/~1~fac~2024~... 2024-03-26 09:00:00   

           source   sub_cat                                          embedding  
0  Femme actuelle  feminine  b'\x00\x00\x00\xe0z7\xb6?\x00\x00\x00@\xb3\xb1...  
1  Femme actuelle  feminine  b'\x00\x00\x00@\xaa\t\x81\xbf\x00\x00\x00@\xac...  
2  Femme actuelle  feminine  b'\x00\x00\x00\xa0\xf0\x98\xba?\x00\x00\x00\xe...  
3  Femme actuelle  feminine  b'\x00\x00\x00@,\xa1m?\x00\x00\x00\xc0z\xec\x9...

In [15]:
title_and_description = result.apply(lambda row: row['title'] + ' ' + row['description'], axis=1)
news_embedded = model.encode(title_and_description)
result['embedding'] = pd.Series(news_embedded.tolist())
result


len(result.iloc[0]['embedding'])


768

In [23]:
encoded = np.array(result.iloc[0]['embedding']).tobytes()
encoded
decoded = np.frombuffer(encoded, dtype=np.float64)
decoded

array([ 8.67840573e-02,  7.30239898e-02,  7.84316435e-02, -9.14108241e-04,
       -9.93116498e-02, -2.00946495e-01,  1.47948071e-01, -4.19272967e-02,
       -3.80542763e-02,  6.14001900e-02, -1.05752245e-01, -4.42148596e-02,
       -3.25332396e-02,  8.79342109e-02, -1.83870390e-01,  8.79555196e-02,
        6.91612437e-03,  1.19129099e-01, -3.38599756e-02,  2.09250301e-01,
        6.53192867e-04,  3.28303277e-02,  2.08483133e-02, -9.88083854e-02,
       -1.43221781e-01,  3.50392275e-02, -6.32063150e-02,  1.25764325e-01,
       -1.90182813e-02, -8.53521377e-03, -8.89038965e-02, -1.06187388e-01,
        3.54545340e-02,  3.45171541e-02, -7.84348845e-02,  6.77185459e-03,
       -7.67049640e-02, -5.15197106e-02, -6.78677335e-02, -1.80180624e-01,
        5.68622649e-02,  1.17513689e-03,  2.17492096e-02,  7.13162720e-02,
       -1.73258819e-02, -5.02051041e-03,  6.05040155e-02,  9.69350189e-02,
       -7.15008453e-02, -4.14521694e-02, -3.44674438e-02,  5.20616360e-02,
        1.43828681e-02,  