# Bert embeddings test

In [2]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer("dangvantuan/sentence-camembert-base")

sentences = ["Un avion est en train de décoller.",
          "Un homme joue d'une grande flûte.",
          "Un homme étale du fromage râpé sur une pizza.",
          "Une personne jette un chat au plafond.",
          "Une personne est en train de plier un morceau de papier.",
          ]

embeddings = model.encode(sentences)
embeddings.shape

(5, 768)

# Create Dataset with embeddings

In [3]:
from ml_logic.data_mysql import db_to_dataframe
news_df = db_to_dataframe(nb_rows=20000)
news_df.head(3)

DataFrame retrieve from MySQL


news_id  category_id                                              title  \
0   129579            8  Enlèvements dans le nord-ouest, le président n...   
1   129580            8  Anta Babacar Ngom, l'unique femme candidate à ...   
2   129581            8  Les leaders musulmans boycottent les célébrati...   

                                         description  \
0  Au Nigeria, plus de 100 personnes ont été enle...   
1  Comme les 17 hommes qui briguent la présidence...   
2  Les dirigeants musulmans américains, indignés ...   

                                                link image  \
0  https://www.voaafrique.com/a/enl%c3%a8vements-...         
1  https://www.voaafrique.com/a/anta-babacar-ngom...         
2  https://www.voaafrique.com/a/les-leaders-musul...         

           added_date                      source sub_cat  \
0 2024-03-22 09:00:00  Voice Of America : Afrique           
1 2024-03-22 09:00:00  Voice Of America : Afrique           
2 2024-03-22 09:00:00  Voice Of America : Afrique           

                                           embedding  
0  b'\x00\x00\x00\x00\x96%\x9d?\x00\x00\x00\x00MZ...  
1  b'\x00\x00\x00\xa0\xd3\xbc\xad?\x00\x00\x00`n ...  
2  b'\x00\x00\x00\xe0\xc4\x8d\x81\xbf\x00\x00\x00...

In [29]:
import pandas as pd

title_and_description = news_df.head(5).apply(lambda row: row['title'] + ' ' + row['description'], axis=1)
news_embedded = model.encode(title_and_description)
news_df['embedding'] = pd.Series(news_embedded.tolist())

Exception during reset or similar
Traceback (most recent call last):
  File "/Users/mathieuna/.pyenv/versions/3.10.6/envs/the_mdr_project/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 986, in _finalize_fairy
    fairy._reset(
  File "/Users/mathieuna/.pyenv/versions/3.10.6/envs/the_mdr_project/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1432, in _reset
    pool._dialect.do_rollback(self)
  File "/Users/mathieuna/.pyenv/versions/3.10.6/envs/the_mdr_project/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 693, in do_rollback
    dbapi_connection.rollback()
  File "/Users/mathieuna/.pyenv/versions/3.10.6/envs/the_mdr_project/lib/python3.10/site-packages/pymysql/connections.py", line 488, in rollback
    self._read_ok_packet()
  File "/Users/mathieuna/.pyenv/versions/3.10.6/envs/the_mdr_project/lib/python3.10/site-packages/pymysql/connections.py", line 448, in _read_ok_packet
    pkt = self._read_packet()
  File "/Users/mathieuna/.pyenv/version

In [49]:
news_df

news_id  category_id  \
0            1            1   
1            2            1   
2            3            1   
3            4            1   
4            5            1   
...        ...          ...   
19995    19996            6   
19996    19997            6   
19997    19998            6   
19998    19999            6   
19999    20000            6   

                                                   title  \
0                       Analyse d’un roman (68e épisode)   
1      Un remake annoncé pour ce film culte des année...   
2      Equilibrium : pourquoi ça aurait dû être un gr...   
3      Furiosa : George Miller explique pourquoi il a...   
4      Ce vidéoprojecteur 4K LG profite d'une remise ...   
...                                                  ...   
19995  Le Medef milite pour « une diplomatie patronal...   
19996  Navigation par satellite : l'Europe s'offre le...   
19997  Air Austral de nouveau dans la tourmente, l'Et...   
19998  Aéronautique : le grand écart au sein de la fi...   
19999  Emmanuel Macron veut relancer le chantier péri...   

                                             description  \
0      Dans ce nouvel épisode de la série « L’Alchimi...   
1      Les producteurs du Discours d'un roi ont annon...   
2      Film de science-fiction sorti au cinéma en 200...   
3      Le réalisateur George Miller est revenu sur la...   
4      Reconnu comme l'un des meilleurs modèles à ult...   
...                                                  ...   
19995  « L'Europe ne doit pas devenir une machine à d...   
19996  L'Agence spatiale européenne a signé des contr...   
19997  Air Austral est de nouveau en forte difficulté...   
19998  Une étude de l'Insee révèle la grande hétérogé...   
19999  Lors de la conférence annuelle d'Euronext, le ...   

                                                    link image  \
0      https://www.aproposdecriture.com/analyse-dun-r...         
1      https://www.ecranlarge.com/films/news/1505931-...         
2      https://www.ecranlarge.com/films/news/1505944-...         
3      https://www.ecranlarge.com/films/news/1505918-...         
4      https://www.ecranlarge.com/high-tech/news/1505...         
...                                                  ...   ...   
19995  https://objectifaquitaine.latribune.fr/busines...         
19996  https://www.latribune.fr/entreprises-finance/i...         
19997  https://www.latribune.fr/entreprises-finance/s...         
19998  https://toulouse.latribune.fr/entreprises/busi...         
19999  https://www.latribune.fr/entreprises-finance/b...         

               added_date                   source      sub_cat  \
0     2024-03-21 09:00:00      À propos d'écriture  litterature   
1     2024-03-21 09:00:00              Écran large       cinema   
2     2024-03-21 09:00:00              Écran large       cinema   
3     2024-03-21 09:00:00              Écran large       cinema   
4     2024-03-21 09:00:00              Écran large       cinema   
...                   ...                      ...          ...   
19995 2024-03-20 09:00:00   La Tribune : Aquitaine       presse   
19996 2024-03-20 09:00:00  La Tribune : entreprise   entreprise   
19997 2024-03-20 09:00:00  La Tribune : entreprise   entreprise   
19998 2024-03-20 09:00:00  La Tribune : entreprise   entreprise   
19999 2024-03-20 09:00:00  La Tribune : entreprise   entreprise   

                                               embedding  
0      [-0.014406162314116955, -0.03601408377289772, ...  
1      [-0.021693894639611244, -0.04296451061964035, ...  
2      [-0.0148801663890481, 0.18702416121959686, -0....  
3      [0.13725970685482025, -0.12948304414749146, 0....  
4      [0.14467690885066986, 0.09902400523424149, -0....  
...                                                  ...  
19995  [0.05735137686133385, -0.07912855595350266, -0...  
19996  [0.042096056044101715, -0.1556801199913025, -0...  
19997  [-0.022747622802853584, -0.013673056848347187,...  
1999

# Compute similarity

In [39]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

def compute_cosine_similarity(first_embedding, second_embedding):
    dot_product = np.dot(first_embedding, second_embedding)

    norm_first_emb = np.linalg.norm(first_embedding)
    norm_second_emb = np.linalg.norm(second_embedding)

    cosine_sim = dot_product / (norm_first_emb * norm_second_emb)
    return cosine_sim

def compute_jaccard_similarity(first_embedding, second_embedding):
    intersection = np.logical_and(first_embedding, second_embedding).sum()
    union = np.logical_or(first_embedding, second_embedding).sum()
    jac_sim = intersection / union if union != 0 else 0
    return jac_sim

def compute_euclidean_distance(first_embedding, second_embedding):
    return np.linalg.norm(first_embedding - second_embedding)

def compute_manhattan_distance(first_embedding, second_embedding):
    return np.sum(np.abs(first_embedding - second_embedding))

In [44]:
from ml_logic.data_mysql import get_last_news_liked

last_liked = get_last_news_liked(3, list(np.arange(1,14))).apply(lambda row: row['title'] + ' ' + row['description'], axis=1)
last_liked_emb = model.encode(last_liked)
last_liked_emb

------------LAST NEWS LIKED BY {user_id} retrieve -------------
   news_id  category_id                                              title  \
0   122971            6  Droits TV – La Ligue Nationale de Rugby (LNR) ...   

                                         description  \
0  A 3 ans de la fin du contrat avec CANAL+, la L...   

                                                link image  \
0  https://www.sportbuzzbusiness.fr/droits-tv-la-...         

           added_date             source sub_cat  
0 2024-03-22 09:00:00  SportBuzzBusiness   sport  
-------------------------


array([[-2.95031425e-02,  5.74099040e-03, -5.19872643e-02,
         4.16139290e-02,  6.83590174e-02, -1.38741106e-01,
         1.15057454e-01,  2.05307156e-02, -2.60392651e-02,
         5.25718518e-02, -2.39394475e-02, -1.67628806e-02,
         5.43239452e-02, -5.53108603e-02, -4.81103696e-02,
         1.93409584e-02,  5.55538535e-02, -2.67953333e-03,
        -4.86991107e-02, -6.88108727e-02, -5.71102127e-02,
        -9.49140117e-02,  2.22731009e-02,  5.79125173e-02,
         9.75076705e-02,  5.20899110e-02,  4.18021791e-02,
         9.13061425e-02,  5.13124280e-02, -4.85926904e-02,
         4.74096090e-02,  8.01393855e-03,  1.07931390e-01,
         7.24832527e-03, -1.13442875e-01,  9.09873396e-02,
         1.46250725e-02, -1.55161753e-01,  1.09530576e-02,
         2.06489135e-02, -1.49738520e-01,  4.08941461e-03,
        -3.78170609e-02,  5.31136431e-03, -1.19858973e-01,
         1.82652436e-02,  3.56878862e-02, -2.41460297e-02,
        -8.08689073e-02, -9.05929282e-02, -1.02815377e-0

In [40]:
def get_top_similar_news(news_embedded, news_df, num_recommendations, method='cosine'):
    # Map method to associated function
    similarity_functions = {
        'cosine': compute_cosine_similarity,
        'euclidean': compute_euclidean_distance,
        'manhattan': compute_manhattan_distance,
        'jaccard': compute_jaccard_similarity
    }
    if method not in similarity_functions:
        raise ValueError("Invalid method. Valid options are 'cosine', 'euclidean', 'manhattan', and 'jaccard'.")

    # Compute the similaritues
    similarity_function = similarity_functions[method]
    similarities = []
    for idx, row in news_df.iterrows():
        similarity = similarity_function(news_embedded, row['embedding'])
        similarities.append((idx, similarity))

    # Retrieve the best news
    if method in ['cosine', 'jaccard']:
        sorted_similarities = sorted(similarities, key=lambda x: x[1], reverse=True)
    else:
        sorted_similarities = sorted(similarities, key=lambda x: x[1])

    top_similar_news_indices = [idx for idx, _ in sorted_similarities[:num_recommendations]]
    top_similar_news = news_df.loc[top_similar_news_indices]

    return top_similar_news

In [46]:
get_top_similar_news(last_liked_emb, news_df, 10, method='cosine')

news_id  category_id  \
5585      5586            5   
7880      7881            6   
5299      5300            5   
5875      5876            5   
17647    17648            5   
6100      6101            5   
4968      4969            5   
15987    15988            3   
5024      5025            5   
3264      3265            3   

                                                   title  \
5585   Droits TV du Top 14 : confiante dans un «conte...   
7880   Droits TV : la Ligue nationale de rugby va lan...   
5299   La LNR s'apprête à lancer un appel d'offres su...   
5875   Rugby: la LNR compte profiter du "contexte trè...   
17647      Droits TV : Et si le Top 14 quittait Canal+ ?   
6100                  Les droits TV bientôt remis en jeu   
4968   LNR : la Ligue prépare un nouvel appel d'offre...   
15987  En course pour remporter les droits de la Ligu...   
5024   Transferts UBB : Clermont a tranché pour Mados...   
3264   Télévision : l’accord de distribution DAZN / C...   

                                             description  \
5585   La Ligue nationale de rugby prépare le nouvel ...   
7880   La Ligue nationale de rugby compte profiter du...   
5299   Emmanuel Eschalier, le directeur général de la...   
5875   La rumeur commençait à enfler, elle est mainte...   
17647  TOP 14 - Selon les informations du Midi Olympi...   
6100   Ce mercredi, le directeur général de la Ligue ...   
4968   La LNR prépare un nouvel appel d'offres pour l...   
15987  Le deal entre Canal+ et DAZN n&#8217;a pas rap...   
5024   TOP 14 2023-2024 - Dans le Midi Olympique, Did...   
3264   Le partenariat entre Canal+ et DAZN n&#8217;a ...   

                                                    link  \
5585   https://www.lefigaro.fr/sports/rugby/top-14/dr...   
7880   https://the-media-leader.fr/droits-tv-la-ligue...   
5299   https://www.lequipe.fr/Medias/Actualites/La-ln...   
5875   https://rmcsport.bfmtv.com/rugby/top-14/rugby-...   
17647  https://dicodusport.fr/blog/droits-tv-et-si-le...   
6100   https://www.sports.fr/rugby/top-14/les-droits-...   
4968   https://www.dailysports.fr/top-14/lnr--la-ligu...   
15987  https://www.universfreebox.com/article/563177/...   
5024   https://dicodusport.fr/blog/transferts-ubb-cle...   
3264   https://www.freenews.fr/freenews-edition-natio...   

                                                   image          added_date  \
5585   https://i.f1g.fr/media/cms/2639x1484_crop/2024... 2024-03-21 09:00:00   
7880                                                     2024-03-21 09:00:00   
5299                                                     2024-03-21 09:00:00   
5875                                                     2024-03-21 09:00:00   
17647                                                    2024-03-20 09:00:00   
6100                                                     2024-03-21 09:00:00   
4968                                                     2024-03-21 09:00:00   
15987                                                    2024-03-20 09:00:00   
5024                                                     2024-03-21 09:00:00   
3264                                                     2024-03-21 09:00:00   

                           source       sub_cat  \
5585            Le Figaro : rugby         rugby   
7880             The Media Leader         media   
5299             L'Équipe : rugby         rugby   
5875                  RMC : rugby         rugby   
17647  Dico du sport : actualités                 
6100            Sports.fr : rugby         rugby   
4968         Daily Sports : photo         photo   
15987      Free : univers freebox  informatique   
5024        Dico du sport : rugby         rugby   
3264                  Free : news  informatique   

                                               embedding  
5585   [-0.027569524943828583, -0.03932572156190872, ...  
7880   [0.023579087108373642, -0.06490983814001083, -...  
5299   [0.024758240208029747, -0.008958631195127964, ...  
587

# Editing DB to add embeddings

In [48]:
import sqlalchemy
from ml_logic.data_mysql import getconn

In [50]:
news_df = db_to_dataframe()

title_and_description = news_df.apply(lambda row: row['title'] + ' ' + row['description'], axis=1)
news_embedded = model.encode(title_and_description)
news_df['embedding'] = pd.Series(news_embedded.tolist())
news_df

DataFrame retrieve from MySQL


news_id  category_id  \
0             1            1   
1             2            1   
2             3            1   
3             4            1   
4             5            1   
...         ...          ...   
127711   129609           12   
127712   129610           12   
127713   129611           12   
127714   129612            6   
127715   129613            6   

                                                    title  \
0                        Analyse d’un roman (68e épisode)   
1       Un remake annoncé pour ce film culte des année...   
2       Equilibrium : pourquoi ça aurait dû être un gr...   
3       Furiosa : George Miller explique pourquoi il a...   
4       Ce vidéoprojecteur 4K LG profite d'une remise ...   
...                                                   ...   
127711  "La princesse va bien, à présent" : Albert II ...   
127712  "J'aurai du mal à en parler au passé" : Stépha...   
127713  L'ancien ministre Frédéric Mitterrand est mort...   
127714  IA : Microsoft déploie les grands moyens pour ...   
127715  Thales Belfast, cette usine qui produit des mi...   

                                              description  \
0       Dans ce nouvel épisode de la série « L’Alchimi...   
1       Les producteurs du Discours d'un roi ont annon...   
2       Film de science-fiction sorti au cinéma en 200...   
3       Le réalisateur George Miller est revenu sur la...   
4       Reconnu comme l'un des meilleurs modèles à ult...   
...                                                   ...   
127711  Le prince Albert II de Monaco s'est confié sur...   
127712  Stéphane Bern a appris en direct la mort de Fr...   
127713  Jeudi 21 mars 2024, Frédéric Mitterrand est dé...   
127714  Sous la houlette de Satya Nadella, le géant in...   
127715  REPORTAGE - L’usine nord-irlandaise de Thales ...   

                                                     link  \
0       https://www.aproposdecriture.com/analyse-dun-r...   
1       https://www.ecranlarge.com/films/news/1505931-...   
2       https://www.ecranlarge.com/films/news/1505944-...   
3       https://www.ecranlarge.com/films/news/1505918-...   
4       https://www.ecranlarge.com/high-tech/news/1505...   
...                                                   ...   
127711  https://www.femmeactuelle.fr/actu/news-actu/la...   
127712  https://www.femmeactuelle.fr/actu/news-actu/j-...   
127713  https://www.femmeactuelle.fr/actu/news-actu/l-...   
127714  https://www.challenges.fr/entreprise/ia-plus-p...   
127715  https://www.challenges.fr/entreprise/defense/g...   

                                                    image          added_date  \
0                                                         2024-03-21 09:00:00   
1                                                         2024-03-21 09:00:00   
2                                                         2024-03-21 09:00:00   
3                                                         2024-03-21 09:00:00   
4                                                         2024-03-21 09:00:00   
...                                                   ...                 ...   
127711  https://fac.img.pmdstatic.net/fit/~1~voi~2023~... 2024-03-22 09:00:00   
127712  https://fac.img.pmdstatic.net/fit/~1~fac~2024~... 2024-03-22 09:00:00   
127713  https://fac.img.pmdstatic.net/fit/~1~fac~2021~... 2024-03-22 09:00:00   
127714                                                    2024-03-22 09:00:00   
127715                                                    2024-03-22 09:00:00   

                     source      sub_cat  \
0       À propos d'écriture  litterature   
1               Écran large       cinema   
2               Écran large       cinema   
3               Écran large       cinema   
4               Écran large       cinema   
...                     ...          ...   
127711       Femme actuelle     feminine   
127712       Femme actuelle     feminine   
127713       Femme actuelle     feminine   
127714     

In [53]:
from ml_logic.data_mysql import getconn

pool = sqlalchemy.create_engine(
        "mysql+pymysql://",
        creator=getconn,
    )
conn = pool.connect()

query = sqlalchemy.text("""
    ALTER TABLE news_dataset
    ADD COLUMN embedding BLOB
""")
conn.execute(query)

In [58]:
pool = sqlalchemy.create_engine(
        "mysql+pymysql://",
        creator=getconn,
    )
conn = pool.connect()

for idx, row in news_df.iterrows():
    params={'embedding': np.array(row['embedding']).tobytes(),
        'news_id': row['news_id']}

    query = sqlalchemy.text("""
        UPDATE news_dataset
        SET embedding = :embedding
        WHERE news_id = :news_id
    """)

    conn.execute(query, parameters=params)

conn.commit()
print("Embeddings added to the database.")

Embeddings added to the database.


# Compute the mean embeddings

In [47]:
def compute_embedding_mean(embeddings):
    if embeddings.empty:
        raise ValueError("The embeddings passed are empty")
    embeddings_array = np.array(embeddings.tolist())
    mean_embedding = np.mean(embeddings_array, axis=0)
    return mean_embedding

# Lecture des embeddings

In [59]:
embeddings_df = db_to_dataframe(10)

decoded_embeddings = []
for idx, row in embeddings_df.iterrows():
    embedding_bytes = row['embedding']
    embedding_array = np.frombuffer(embedding_bytes, dtype=np.float32)
    decoded_embeddings.append(embedding_array)

decoded_embeddings

DataFrame retrieve from MySQL


[array([ 3.6893488e+19, -1.1054986e+00,  1.0842022e-19, ...,
        -1.3972992e+00,  2.0000000e+00,  1.1855617e+00], dtype=float32),
 array([-1.0842022e-19, -1.1735511e+00, -2.0000000e+00, ...,
        -1.3615949e+00, -2.0000000e+00,  1.4499897e+00], dtype=float32),
 array([ 1.0842022e-19, -1.1130826e+00,  3.6893488e+19, ...,
         1.3966033e+00, -0.0000000e+00,  1.3920240e+00], dtype=float32),
 array([-3.6893488e+19,  1.5122596e+00, -0.0000000e+00, ...,
         1.1705309e+00, -3.6893488e+19,  1.2049527e+00], dtype=float32),
 array([-3.6893488e+19,  1.5196768e+00,  1.0842022e-19, ...,
        -8.5178334e-01, -3.6893488e+19,  1.3439808e+00], dtype=float32),
 array([-2.        , -0.812992  , -0.        , ...,  0.96295124,
         2.        , -1.2015364 ], dtype=float32),
 array([-1.0842022e-19, -1.2842952e+00,  2.0000000e+00, ...,
         1.0631794e+00, -3.6893488e+19,  1.5069513e+00], dtype=float32),
 array([-0.       , -1.275765 , -0.       , ...,  0.9794823, -0.       ,
       

['the-mdr-project:europe-west1:mdr-project']: An error occurred while performing refresh. Scheduling another refresh attempt immediately
Traceback (most recent call last):
  File "/Users/mathieuna/.pyenv/versions/3.10.6/envs/the_mdr_project/lib/python3.10/site-packages/google/cloud/sql/connector/instance.py", line 312, in _refresh_task
    refresh_data = await refresh_task
  File "/Users/mathieuna/.pyenv/versions/3.10.6/envs/the_mdr_project/lib/python3.10/site-packages/google/cloud/sql/connector/instance.py", line 260, in _perform_refresh
    ephemeral_cert, expiration = await ephemeral_task
  File "/Users/mathieuna/.pyenv/versions/3.10.6/envs/the_mdr_project/lib/python3.10/site-packages/google/cloud/sql/connector/client.py", line 193, in _get_ephemeral
    resp = await self._client.post(
  File "/Users/mathieuna/.pyenv/versions/3.10.6/envs/the_mdr_project/lib/python3.10/site-packages/aiohttp/client.py", line 605, in _request
    await resp.start(conn)
  File "/Users/mathieuna/.pyenv/v